# Anna KaRNNa

In this notebook, I'll build a character-wise RNN trained on Anna Karenina, one of my all-time favorite books. It'll be able to generate new text based on the text from the book.

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). Also, some information [here at r2rt](http://r2rt.com/recurrent-neural-networks-in-tensorflow-ii.html) and from [Sherjil Ozair](https://github.com/sherjilozair/char-rnn-tensorflow) on GitHub. Below is the general architecture of the character-wise RNN.

<img src="assets/charseq.jpeg" width="500">

In [1]:
import time
from collections import namedtuple

import numpy as np
import tensorflow as tf

First we'll load the text file and convert it into integers for our network to use. Here I'm creating a couple dictionaries to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [2]:
with open('anna.txt', 'r') as f:
    text=f.read()
vocab = sorted(set(text))
vocab_to_int = {c: i for i, c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)

Let's check out the first 100 characters, make sure everything is peachy. According to the [American Book Review](http://americanbookreview.org/100bestlines.asp), this is the 6th best first line of a book ever.

In [3]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

And we can see the characters encoded as integers.

In [4]:
encoded[:100]

array([31, 64, 57, 72, 76, 61, 74,  1, 16,  0,  0,  0, 36, 57, 72, 72, 81,
        1, 62, 57, 69, 65, 68, 65, 61, 75,  1, 57, 74, 61,  1, 57, 68, 68,
        1, 57, 68, 65, 67, 61, 26,  1, 61, 78, 61, 74, 81,  1, 77, 70, 64,
       57, 72, 72, 81,  1, 62, 57, 69, 65, 68, 81,  1, 65, 75,  1, 77, 70,
       64, 57, 72, 72, 81,  1, 65, 70,  1, 65, 76, 75,  1, 71, 79, 70,  0,
       79, 57, 81, 13,  0,  0, 33, 78, 61, 74, 81, 76, 64, 65, 70], dtype=int32)

Since the network is working with individual characters, it's similar to a classification problem in which we are trying to predict the next character from the previous text.  Here's how many 'classes' our network has to pick from.

In [6]:
len(vocab)

83

## Making training mini-batches

Here is where we'll make our mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>
We have our text encoded as integers as one long array in `encoded`. Let's create a function that will give us an iterator for our batches. I like using [generator functions](https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/) to do this. Then we can pass `encoded` into this function and get our batch generator.

The first thing we need to do is discard some of the text so we only have completely full batches. Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences) and $M$ is the number of steps. Then, to get the number of batches we can make from some array `arr`, you divide the length of `arr` by the batch size. Once you know the number of batches and the batch size, you can get the total number of characters to keep.

After that, we need to split `arr` into $N$ sequences. You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences (`n_seqs` below), let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$ where $K$ is the number of batches.

Now that we have this array, we can iterate through it to get our batches. The idea is each batch is a $N \times M$ window on the array. For each subsequent batch, the window moves over by `n_steps`. We also want to create both the input and target arrays. Remember that the targets are the inputs shifted over one character. You'll usually see the first input character used as the last target character, so something like this:
```python
y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
```
where `x` is the input batch and `y` is the target batch.

The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of steps in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `n_steps` wide.

In [7]:
def get_batches(arr, n_seqs, n_steps):
    '''Create a generator that returns batches of size
       n_seqs x n_steps from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       n_seqs: Batch size, the number of sequences per batch
       n_steps: Number of sequence steps per batch
    '''
    # Get the number of characters per batch and number of batches we can make
    characters_per_batch = n_seqs * n_steps
    n_batches = len(arr)//characters_per_batch
    
    # Keep only enough characters to make full batches
    arr = arr[:n_batches * characters_per_batch]
    
    # Reshape into n_seqs rows
    arr = arr.reshape((n_seqs, -1))
    
    for n in range(0, arr.shape[1], n_steps):
        # The features
        x = arr[:, n:n+n_steps]
        # The targets, shifted by one
        y = np.zeros_like(x)
        y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
        yield x, y

Now I'll make my data sets and we can check out what's going on here. Here I'm going to use a batch size of 10 and 50 sequence steps.

In [8]:
batches = get_batches(encoded, 10, 50)
x, y = next(batches)

In [9]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[31 64 57 72 76 61 74  1 16  0]
 [ 1 57 69  1 70 71 76  1 63 71]
 [78 65 70 13  0  0  3 53 61 75]
 [70  1 60 77 74 65 70 63  1 64]
 [ 1 65 76  1 65 75 11  1 75 65]
 [ 1 37 76  1 79 57 75  0 71 70]
 [64 61 70  1 59 71 69 61  1 62]
 [26  1 58 77 76  1 70 71 79  1]
 [76  1 65 75 70  7 76 13  1 48]
 [ 1 75 57 65 60  1 76 71  1 64]]

y
 [[64 57 72 76 61 74  1 16  0  0]
 [57 69  1 70 71 76  1 63 71 65]
 [65 70 13  0  0  3 53 61 75 11]
 [ 1 60 77 74 65 70 63  1 64 65]
 [65 76  1 65 75 11  1 75 65 74]
 [37 76  1 79 57 75  0 71 70 68]
 [61 70  1 59 71 69 61  1 62 71]
 [ 1 58 77 76  1 70 71 79  1 75]
 [ 1 65 75 70  7 76 13  1 48 64]
 [75 57 65 60  1 76 71  1 64 61]]


If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[55 63 69 22  6 76 45  5 16 35]
 [ 5 69  1  5 12 52  6  5 56 52]
 [48 29 12 61 35 35  8 64 76 78]
 [12  5 24 39 45 29 12 56  5 63]
 [ 5 29  6  5 29 78 28  5 78 29]
 [ 5 13  6  5 36 69 78 35 52 12]
 [63 76 12  5 18 52  1 76  5 58]
 [34  5 73 39  6  5 12 52 36  5]
 [ 6  5 29 78 12 79  6 61  5 59]
 [ 5 78 69 29 24  5  6 52  5 63]]

y
 [[63 69 22  6 76 45  5 16 35 35]
 [69  1  5 12 52  6  5 56 52 29]
 [29 12 61 35 35  8 64 76 78 28]
 [ 5 24 39 45 29 12 56  5 63 29]
 [29  6  5 29 78 28  5 78 29 45]
 [13  6  5 36 69 78 35 52 12 43]
 [76 12  5 18 52  1 76  5 58 52]
 [ 5 73 39  6  5 12 52 36  5 78]
 [ 5 29 78 12 79  6 61  5 59 63]
 [78 69 29 24  5  6 52  5 63 76]]
 ```
 although the exact numbers will be different. Check to make sure the data is shifted over one step for `y`.

## Building the model

Below is where you'll build the network. We'll break it up into parts so it's easier to reason about each bit. Then we can connect them up into the whole network.

<img src="assets/charRNN.png" width=500px>


### Inputs

First off we'll create our input placeholders. As usual we need placeholders for the training data and the targets. We'll also create a placeholder for dropout layers called `keep_prob`.

In [10]:
def build_inputs(batch_size, num_steps):
    ''' Define placeholders for inputs, targets, and dropout 
    
        Arguments
        ---------
        batch_size: Batch size, number of sequences per batch
        num_steps: Number of sequence steps in a batch
        
    '''
    # Declare placeholders we'll feed into the graph
    inputs = tf.placeholder(tf.int32, [batch_size, num_steps], name='inputs')
    targets = tf.placeholder(tf.int32, [batch_size, num_steps], name='targets')
    
    # Keep probability placeholder for drop out layers
    keep_prob = tf.placeholder(tf.float32, name='keep_prob')
    
    return inputs, targets, keep_prob

### LSTM Cell

Here we will create the LSTM cell we'll use in the hidden layer. We'll use this cell as a building block for the RNN. So we aren't actually defining the RNN here, just the type of cell we'll use in the hidden layer.

We first create a basic LSTM cell with

```python
lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
```

where `num_units` is the number of units in the hidden layers in the cell. Then we can add dropout by wrapping it with 

```python
tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
```
You pass in a cell and it will automatically add dropout to the inputs or outputs. Finally, we can stack up the LSTM cells into layers with [`tf.contrib.rnn.MultiRNNCell`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/rnn/MultiRNNCell). With this, you pass in a list of cells and it will send the output of one cell into the next cell. Previously with TensorFlow 1.0, you could do this

```python
tf.contrib.rnn.MultiRNNCell([cell]*num_layers)
```

This might look a little weird if you know Python well because this will create a list of the same `cell` object. However, TensorFlow 1.0 will create different weight matrices for all `cell` objects. But, starting with TensorFlow 1.1 you actually need to create new cell objects in the list. To get it to work in TensorFlow 1.1, it should look like

```python
def build_cell(num_units, keep_prob):
    lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
    drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
    
    return drop
    
tf.contrib.rnn.MultiRNNCell([build_cell(num_units, keep_prob) for _ in range(num_layers)])
```

Even though this is actually multiple LSTM cells stacked on each other, you can treat the multiple layers as one cell.

We also need to create an initial cell state of all zeros. This can be done like so

```python
initial_state = cell.zero_state(batch_size, tf.float32)
```

Below, we implement the `build_lstm` function to create these LSTM cells and the initial state.

In [11]:
def build_lstm(lstm_size, num_layers, batch_size, keep_prob):
    ''' Build LSTM cell.
    
        Arguments
        ---------
        keep_prob: Scalar tensor (tf.placeholder) for the dropout keep probability
        lstm_size: Size of the hidden layers in the LSTM cells
        num_layers: Number of LSTM layers
        batch_size: Batch size

    '''
    ### Build the LSTM Cell
    
    def build_cell(lstm_size, keep_prob):
        # Use a basic LSTM cell
        lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
        
        # Add dropout to the cell
        drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
        return drop
    
    
    # Stack up multiple LSTM layers, for deep learning
    cell = tf.contrib.rnn.MultiRNNCell([build_cell(lstm_size, keep_prob) for _ in range(num_layers)])
    initial_state = cell.zero_state(batch_size, tf.float32)
    
    return cell, initial_state

### RNN Output

Here we'll create the output layer. We need to connect the output of the RNN cells to a full connected layer with a softmax output. The softmax output gives us a probability distribution we can use to predict the next character.

If our input has batch size $N$, number of steps $M$, and the hidden layer has $L$ hidden units, then the output is a 3D tensor with size $N \times M \times L$. The output of each LSTM cell has size $L$, we have $M$ of them, one for each sequence step, and we have $N$ sequences. So the total size is $N \times M \times L$.

We are using the same fully connected layer, the same weights, for each of the outputs. Then, to make things easier, we should reshape the outputs into a 2D tensor with shape $(M * N) \times L$. That is, one row for each sequence and step, where the values of each row are the output from the LSTM cells.

One we have the outputs reshaped, we can do the matrix multiplication with the weights. We need to wrap the weight and bias variables in a variable scope with `tf.variable_scope(scope_name)` because there are weights being created in the LSTM cells. TensorFlow will throw an error if the weights created here have the same names as the weights created in the LSTM cells, which they will be default. To avoid this, we wrap the variables in a variable scope so we can give them unique names.

In [12]:
def build_output(lstm_output, in_size, out_size):
    ''' Build a softmax layer, return the softmax output and logits.
    
        Arguments
        ---------
        
        x: Input tensor
        in_size: Size of the input tensor, for example, size of the LSTM cells
        out_size: Size of this softmax layer
    
    '''

    # Reshape output so it's a bunch of rows, one row for each step for each sequence.
    # That is, the shape should be batch_size*num_steps rows by lstm_size columns
    seq_output = tf.concat(lstm_output, axis=1)
    x = tf.reshape(seq_output, [-1, in_size])
    
    # Connect the RNN outputs to a softmax layer
    with tf.variable_scope('softmax'):
        softmax_w = tf.Variable(tf.truncated_normal((in_size, out_size), stddev=0.1))
        softmax_b = tf.Variable(tf.zeros(out_size))
    
    # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
    # of rows of logit outputs, one for each step and sequence
    logits = tf.matmul(x, softmax_w) + softmax_b
    
    # Use softmax to get the probabilities for predicted characters
    out = tf.nn.softmax(logits, name='predictions')
    
    return out, logits

### Training loss

Next up is the training loss. We get the logits and targets and calculate the softmax cross-entropy loss. First we need to one-hot encode the targets, we're getting them as encoded characters. Then, reshape the one-hot targets so it's a 2D tensor with size $(M*N) \times C$ where $C$ is the number of classes/characters we have. Remember that we reshaped the LSTM outputs and ran them through a fully connected layer with $C$ units. So our logits will also have size $(M*N) \times C$.

Then we run the logits and targets through `tf.nn.softmax_cross_entropy_with_logits` and find the mean to get the loss.

In [13]:
def build_loss(logits, targets, lstm_size, num_classes):
    ''' Calculate the loss from the logits and the targets.
    
        Arguments
        ---------
        logits: Logits from final fully connected layer
        targets: Targets for supervised learning
        lstm_size: Number of LSTM hidden units
        num_classes: Number of classes in targets
        
    '''
    
    # One-hot encode targets and reshape to match logits, one row per batch_size per step
    y_one_hot = tf.one_hot(targets, num_classes)
    y_reshaped = tf.reshape(y_one_hot, logits.get_shape())
    
    # Softmax cross entropy loss
    loss = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_reshaped)
    loss = tf.reduce_mean(loss)
    return loss

### Optimizer

Here we build the optimizer. Normal RNNs have have issues gradients exploding and disappearing. LSTMs fix the disappearance problem, but the gradients can still grow without bound. To fix this, we can clip the gradients above some threshold. That is, if a gradient is larger than that threshold, we set it to the threshold. This will ensure the gradients never grow overly large. Then we use an AdamOptimizer for the learning step.

In [14]:
def build_optimizer(loss, learning_rate, grad_clip):
    ''' Build optmizer for training, using gradient clipping.
    
        Arguments:
        loss: Network loss
        learning_rate: Learning rate for optimizer
    
    '''
    
    # Optimizer for training, using gradient clipping to control exploding gradients
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), grad_clip)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

### Build the network

Now we can put all the pieces together and build a class for the network. To actually run data through the LSTM cells, we will use [`tf.nn.dynamic_rnn`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/nn/dynamic_rnn). This function will pass the hidden and cell states across LSTM cells appropriately for us. It returns the outputs for each LSTM cell at each step for each sequence in the mini-batch. It also gives us the final LSTM state. We want to save this state as `final_state` so we can pass it to the first LSTM cell in the the next mini-batch run. For `tf.nn.dynamic_rnn`, we pass in the cell and initial state we get from `build_lstm`, as well as our input sequences. Also, we need to one-hot encode the inputs before going into the RNN. 

In [15]:
class CharRNN:
    
    def __init__(self, num_classes, batch_size=64, num_steps=50, 
                       lstm_size=128, num_layers=2, learning_rate=0.001, 
                       grad_clip=5, sampling=False):
    
        # When we're using this network for sampling later, we'll be passing in
        # one character at a time, so providing an option for that
        if sampling == True:
            batch_size, num_steps = 1, 1
        else:
            batch_size, num_steps = batch_size, num_steps

        tf.reset_default_graph()
        
        # Build the input placeholder tensors
        self.inputs, self.targets, self.keep_prob = build_inputs(batch_size, num_steps)

        # Build the LSTM cell
        cell, self.initial_state = build_lstm(lstm_size, num_layers, batch_size, self.keep_prob)

        ### Run the data through the RNN layers
        # First, one-hot encode the input tokens
        x_one_hot = tf.one_hot(self.inputs, num_classes)
        
        # Run each sequence step through the RNN and collect the outputs
        outputs, state = tf.nn.dynamic_rnn(cell, x_one_hot, initial_state=self.initial_state)
        self.final_state = state
        
        # Get softmax predictions and logits
        self.prediction, self.logits = build_output(outputs, lstm_size, num_classes)
        
        # Loss and optimizer (with gradient clipping)
        self.loss = build_loss(self.logits, self.targets, lstm_size, num_classes)
        self.optimizer = build_optimizer(self.loss, learning_rate, grad_clip)

## Hyperparameters

Here I'm defining the hyperparameters for the network. 

* `batch_size` - Number of sequences running through the network in one pass.
* `num_steps` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lstm_size` - The number of units in the hidden layers.
* `num_layers` - Number of hidden LSTM layers to use
* `learning_rate` - Learning rate for training
* `keep_prob` - The dropout keep probability when training. If you're network is overfitting, try decreasing this.

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `lstm_size` and `num_layers`. I would advise that you always use `num_layers` of either 2/3. The `lstm_size` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `lstm_size` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.


In [16]:
batch_size = 100        # Sequences per batch
num_steps = 100         # Number of sequence steps per batch
lstm_size = 512         # Size of hidden layers in LSTMs
num_layers = 2          # Number of LSTM layers
learning_rate = 0.001   # Learning rate
keep_prob = 0.5         # Dropout keep probability

## Time for training

This is typical training code, passing inputs and targets into the network, then running the optimizer. Here we also get back the final LSTM state for the mini-batch. Then, we pass that state back into the network so the next batch can continue the state from the previous batch. And every so often (set by `save_every_n`) I save a checkpoint.

Here I'm saving checkpoints with the format

`i{iteration number}_l{# hidden layer units}.ckpt`

In [17]:
epochs = 20
# Save every N iterations
save_every_n = 200

model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    counter = 0
    for e in range(epochs):
        # Train network
        new_state = sess.run(model.initial_state)
        loss = 0
        for x, y in get_batches(encoded, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed = {model.inputs: x,
                    model.targets: y,
                    model.keep_prob: keep_prob,
                    model.initial_state: new_state}
            batch_loss, new_state, _ = sess.run([model.loss, 
                                                 model.final_state, 
                                                 model.optimizer], 
                                                 feed_dict=feed)
            
            end = time.time()
            print('Epoch: {}/{}... '.format(e+1, epochs),
                  'Training Step: {}... '.format(counter),
                  'Training loss: {:.4f}... '.format(batch_loss),
                  '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

Epoch: 1/20...  Training Step: 1...  Training loss: 4.4206...  17.1224 sec/batch
Epoch: 1/20...  Training Step: 2...  Training loss: 4.3305...  14.0747 sec/batch
Epoch: 1/20...  Training Step: 3...  Training loss: 3.8574...  14.3327 sec/batch
Epoch: 1/20...  Training Step: 4...  Training loss: 5.2415...  14.0171 sec/batch
Epoch: 1/20...  Training Step: 5...  Training loss: 4.3354...  14.5475 sec/batch
Epoch: 1/20...  Training Step: 6...  Training loss: 3.8991...  13.8566 sec/batch
Epoch: 1/20...  Training Step: 7...  Training loss: 3.7242...  13.9260 sec/batch
Epoch: 1/20...  Training Step: 8...  Training loss: 3.5782...  13.8914 sec/batch
Epoch: 1/20...  Training Step: 9...  Training loss: 3.4858...  14.6064 sec/batch
Epoch: 1/20...  Training Step: 10...  Training loss: 3.4521...  15.3699 sec/batch
Epoch: 1/20...  Training Step: 11...  Training loss: 3.4171...  16.3956 sec/batch
Epoch: 1/20...  Training Step: 12...  Training loss: 3.4012...  14.3758 sec/batch
Epoch: 1/20...  Training 

Epoch: 1/20...  Training Step: 102...  Training loss: 3.0627...  7.3297 sec/batch
Epoch: 1/20...  Training Step: 103...  Training loss: 3.0867...  7.4399 sec/batch
Epoch: 1/20...  Training Step: 104...  Training loss: 3.0748...  8.5007 sec/batch
Epoch: 1/20...  Training Step: 105...  Training loss: 3.0929...  8.7160 sec/batch
Epoch: 1/20...  Training Step: 106...  Training loss: 3.0865...  7.1440 sec/batch
Epoch: 1/20...  Training Step: 107...  Training loss: 3.0486...  7.4718 sec/batch
Epoch: 1/20...  Training Step: 108...  Training loss: 3.0572...  7.0819 sec/batch
Epoch: 1/20...  Training Step: 109...  Training loss: 3.0634...  7.4083 sec/batch
Epoch: 1/20...  Training Step: 110...  Training loss: 3.0376...  7.1628 sec/batch
Epoch: 1/20...  Training Step: 111...  Training loss: 3.0476...  8.0659 sec/batch
Epoch: 1/20...  Training Step: 112...  Training loss: 3.0507...  7.2936 sec/batch
Epoch: 1/20...  Training Step: 113...  Training loss: 3.0317...  7.9053 sec/batch
Epoch: 1/20...  

Epoch: 2/20...  Training Step: 202...  Training loss: 2.4756...  7.4055 sec/batch
Epoch: 2/20...  Training Step: 203...  Training loss: 2.4692...  7.5801 sec/batch
Epoch: 2/20...  Training Step: 204...  Training loss: 2.4679...  7.8619 sec/batch
Epoch: 2/20...  Training Step: 205...  Training loss: 2.4645...  8.4519 sec/batch
Epoch: 2/20...  Training Step: 206...  Training loss: 2.4616...  7.5153 sec/batch
Epoch: 2/20...  Training Step: 207...  Training loss: 2.4836...  8.3518 sec/batch
Epoch: 2/20...  Training Step: 208...  Training loss: 2.4477...  7.8676 sec/batch
Epoch: 2/20...  Training Step: 209...  Training loss: 2.4393...  8.4925 sec/batch
Epoch: 2/20...  Training Step: 210...  Training loss: 2.4542...  8.3312 sec/batch
Epoch: 2/20...  Training Step: 211...  Training loss: 2.4383...  8.3959 sec/batch
Epoch: 2/20...  Training Step: 212...  Training loss: 2.4610...  6.6928 sec/batch
Epoch: 2/20...  Training Step: 213...  Training loss: 2.4462...  7.9418 sec/batch
Epoch: 2/20...  

Epoch: 2/20...  Training Step: 302...  Training loss: 2.2227...  7.3762 sec/batch
Epoch: 2/20...  Training Step: 303...  Training loss: 2.2127...  7.1084 sec/batch
Epoch: 2/20...  Training Step: 304...  Training loss: 2.2324...  7.0273 sec/batch
Epoch: 2/20...  Training Step: 305...  Training loss: 2.2236...  6.8115 sec/batch
Epoch: 2/20...  Training Step: 306...  Training loss: 2.2471...  7.6326 sec/batch
Epoch: 2/20...  Training Step: 307...  Training loss: 2.2396...  7.0125 sec/batch
Epoch: 2/20...  Training Step: 308...  Training loss: 2.2151...  6.3983 sec/batch
Epoch: 2/20...  Training Step: 309...  Training loss: 2.2244...  6.5743 sec/batch
Epoch: 2/20...  Training Step: 310...  Training loss: 2.2337...  6.9924 sec/batch
Epoch: 2/20...  Training Step: 311...  Training loss: 2.2063...  7.4768 sec/batch
Epoch: 2/20...  Training Step: 312...  Training loss: 2.2047...  6.8101 sec/batch
Epoch: 2/20...  Training Step: 313...  Training loss: 2.2100...  8.0284 sec/batch
Epoch: 2/20...  

Epoch: 3/20...  Training Step: 402...  Training loss: 2.0555...  6.2456 sec/batch
Epoch: 3/20...  Training Step: 403...  Training loss: 2.0860...  6.1584 sec/batch
Epoch: 3/20...  Training Step: 404...  Training loss: 2.0917...  6.2156 sec/batch
Epoch: 3/20...  Training Step: 405...  Training loss: 2.1255...  7.6265 sec/batch
Epoch: 3/20...  Training Step: 406...  Training loss: 2.0724...  9.9695 sec/batch
Epoch: 3/20...  Training Step: 407...  Training loss: 2.0729...  9.7035 sec/batch
Epoch: 3/20...  Training Step: 408...  Training loss: 2.0642...  9.9070 sec/batch
Epoch: 3/20...  Training Step: 409...  Training loss: 2.0708...  10.5975 sec/batch
Epoch: 3/20...  Training Step: 410...  Training loss: 2.1082...  9.4385 sec/batch
Epoch: 3/20...  Training Step: 411...  Training loss: 2.0691...  9.6336 sec/batch
Epoch: 3/20...  Training Step: 412...  Training loss: 2.0518...  8.7498 sec/batch
Epoch: 3/20...  Training Step: 413...  Training loss: 2.0609...  12.2454 sec/batch
Epoch: 3/20...

Epoch: 3/20...  Training Step: 502...  Training loss: 1.9715...  7.1559 sec/batch
Epoch: 3/20...  Training Step: 503...  Training loss: 1.9561...  7.3035 sec/batch
Epoch: 3/20...  Training Step: 504...  Training loss: 1.9756...  7.2287 sec/batch
Epoch: 3/20...  Training Step: 505...  Training loss: 1.9837...  6.9993 sec/batch
Epoch: 3/20...  Training Step: 506...  Training loss: 1.9652...  6.2196 sec/batch
Epoch: 3/20...  Training Step: 507...  Training loss: 1.9617...  6.2051 sec/batch
Epoch: 3/20...  Training Step: 508...  Training loss: 1.9466...  6.2711 sec/batch
Epoch: 3/20...  Training Step: 509...  Training loss: 1.9529...  6.1416 sec/batch
Epoch: 3/20...  Training Step: 510...  Training loss: 1.9459...  6.2759 sec/batch
Epoch: 3/20...  Training Step: 511...  Training loss: 1.9345...  8.3751 sec/batch
Epoch: 3/20...  Training Step: 512...  Training loss: 1.9104...  7.9345 sec/batch
Epoch: 3/20...  Training Step: 513...  Training loss: 1.9557...  10.1128 sec/batch
Epoch: 3/20... 

Epoch: 4/20...  Training Step: 602...  Training loss: 1.8537...  8.2642 sec/batch
Epoch: 4/20...  Training Step: 603...  Training loss: 1.9123...  7.5612 sec/batch
Epoch: 4/20...  Training Step: 604...  Training loss: 1.8554...  7.2101 sec/batch
Epoch: 4/20...  Training Step: 605...  Training loss: 1.8454...  8.0698 sec/batch
Epoch: 4/20...  Training Step: 606...  Training loss: 1.8520...  7.3922 sec/batch
Epoch: 4/20...  Training Step: 607...  Training loss: 1.8677...  10.2435 sec/batch
Epoch: 4/20...  Training Step: 608...  Training loss: 1.9088...  6.6751 sec/batch
Epoch: 4/20...  Training Step: 609...  Training loss: 1.8626...  6.4217 sec/batch
Epoch: 4/20...  Training Step: 610...  Training loss: 1.8448...  8.3387 sec/batch
Epoch: 4/20...  Training Step: 611...  Training loss: 1.8649...  8.5014 sec/batch
Epoch: 4/20...  Training Step: 612...  Training loss: 1.9032...  8.8029 sec/batch
Epoch: 4/20...  Training Step: 613...  Training loss: 1.8727...  7.9657 sec/batch
Epoch: 4/20... 

Epoch: 4/20...  Training Step: 702...  Training loss: 1.7947...  7.3992 sec/batch
Epoch: 4/20...  Training Step: 703...  Training loss: 1.8055...  7.1609 sec/batch
Epoch: 4/20...  Training Step: 704...  Training loss: 1.8060...  7.0256 sec/batch
Epoch: 4/20...  Training Step: 705...  Training loss: 1.7921...  6.4769 sec/batch
Epoch: 4/20...  Training Step: 706...  Training loss: 1.7895...  6.6042 sec/batch
Epoch: 4/20...  Training Step: 707...  Training loss: 1.7981...  7.1063 sec/batch
Epoch: 4/20...  Training Step: 708...  Training loss: 1.7819...  6.9118 sec/batch
Epoch: 4/20...  Training Step: 709...  Training loss: 1.7642...  7.0288 sec/batch
Epoch: 4/20...  Training Step: 710...  Training loss: 1.7502...  6.7964 sec/batch
Epoch: 4/20...  Training Step: 711...  Training loss: 1.7857...  7.7737 sec/batch
Epoch: 4/20...  Training Step: 712...  Training loss: 1.7737...  7.1946 sec/batch
Epoch: 4/20...  Training Step: 713...  Training loss: 1.7805...  7.8615 sec/batch
Epoch: 4/20...  

Epoch: 5/20...  Training Step: 802...  Training loss: 1.7286...  7.7151 sec/batch
Epoch: 5/20...  Training Step: 803...  Training loss: 1.7121...  7.5230 sec/batch
Epoch: 5/20...  Training Step: 804...  Training loss: 1.7140...  7.4356 sec/batch
Epoch: 5/20...  Training Step: 805...  Training loss: 1.7289...  7.8378 sec/batch
Epoch: 5/20...  Training Step: 806...  Training loss: 1.7631...  7.3367 sec/batch
Epoch: 5/20...  Training Step: 807...  Training loss: 1.7217...  7.3137 sec/batch
Epoch: 5/20...  Training Step: 808...  Training loss: 1.7126...  7.4342 sec/batch
Epoch: 5/20...  Training Step: 809...  Training loss: 1.7287...  7.4966 sec/batch
Epoch: 5/20...  Training Step: 810...  Training loss: 1.7616...  7.3488 sec/batch
Epoch: 5/20...  Training Step: 811...  Training loss: 1.7371...  7.1472 sec/batch
Epoch: 5/20...  Training Step: 812...  Training loss: 1.7459...  7.3495 sec/batch
Epoch: 5/20...  Training Step: 813...  Training loss: 1.7130...  7.3528 sec/batch
Epoch: 5/20...  

Epoch: 5/20...  Training Step: 902...  Training loss: 1.6919...  7.9309 sec/batch
Epoch: 5/20...  Training Step: 903...  Training loss: 1.6671...  8.4729 sec/batch
Epoch: 5/20...  Training Step: 904...  Training loss: 1.6771...  8.9095 sec/batch
Epoch: 5/20...  Training Step: 905...  Training loss: 1.6759...  8.0318 sec/batch
Epoch: 5/20...  Training Step: 906...  Training loss: 1.6614...  7.9710 sec/batch
Epoch: 5/20...  Training Step: 907...  Training loss: 1.6577...  7.6744 sec/batch
Epoch: 5/20...  Training Step: 908...  Training loss: 1.6398...  8.0315 sec/batch
Epoch: 5/20...  Training Step: 909...  Training loss: 1.6811...  7.7742 sec/batch
Epoch: 5/20...  Training Step: 910...  Training loss: 1.6655...  8.5120 sec/batch
Epoch: 5/20...  Training Step: 911...  Training loss: 1.6607...  8.2790 sec/batch
Epoch: 5/20...  Training Step: 912...  Training loss: 1.6630...  9.0044 sec/batch
Epoch: 5/20...  Training Step: 913...  Training loss: 1.6724...  9.4347 sec/batch
Epoch: 5/20...  

Epoch: 6/20...  Training Step: 1002...  Training loss: 1.6129...  7.3574 sec/batch
Epoch: 6/20...  Training Step: 1003...  Training loss: 1.6130...  8.8794 sec/batch
Epoch: 6/20...  Training Step: 1004...  Training loss: 1.6630...  7.2311 sec/batch
Epoch: 6/20...  Training Step: 1005...  Training loss: 1.6165...  6.8540 sec/batch
Epoch: 6/20...  Training Step: 1006...  Training loss: 1.6226...  7.1659 sec/batch
Epoch: 6/20...  Training Step: 1007...  Training loss: 1.6473...  7.9753 sec/batch
Epoch: 6/20...  Training Step: 1008...  Training loss: 1.6674...  8.2362 sec/batch
Epoch: 6/20...  Training Step: 1009...  Training loss: 1.6444...  7.4032 sec/batch
Epoch: 6/20...  Training Step: 1010...  Training loss: 1.6518...  7.1825 sec/batch
Epoch: 6/20...  Training Step: 1011...  Training loss: 1.6241...  8.1056 sec/batch
Epoch: 6/20...  Training Step: 1012...  Training loss: 1.6603...  8.6529 sec/batch
Epoch: 6/20...  Training Step: 1013...  Training loss: 1.6306...  7.6819 sec/batch
Epoc

Epoch: 6/20...  Training Step: 1101...  Training loss: 1.5811...  6.6491 sec/batch
Epoch: 6/20...  Training Step: 1102...  Training loss: 1.5931...  6.1121 sec/batch
Epoch: 6/20...  Training Step: 1103...  Training loss: 1.5845...  6.2209 sec/batch
Epoch: 6/20...  Training Step: 1104...  Training loss: 1.5774...  6.1360 sec/batch
Epoch: 6/20...  Training Step: 1105...  Training loss: 1.5716...  6.0849 sec/batch
Epoch: 6/20...  Training Step: 1106...  Training loss: 1.5465...  6.2872 sec/batch
Epoch: 6/20...  Training Step: 1107...  Training loss: 1.5929...  6.1289 sec/batch
Epoch: 6/20...  Training Step: 1108...  Training loss: 1.5880...  6.1471 sec/batch
Epoch: 6/20...  Training Step: 1109...  Training loss: 1.5821...  6.1676 sec/batch
Epoch: 6/20...  Training Step: 1110...  Training loss: 1.5751...  6.1801 sec/batch
Epoch: 6/20...  Training Step: 1111...  Training loss: 1.5889...  6.1116 sec/batch
Epoch: 6/20...  Training Step: 1112...  Training loss: 1.5372...  6.1304 sec/batch
Epoc

Epoch: 7/20...  Training Step: 1200...  Training loss: 1.5275...  6.1763 sec/batch
Epoch: 7/20...  Training Step: 1201...  Training loss: 1.5386...  6.1465 sec/batch
Epoch: 7/20...  Training Step: 1202...  Training loss: 1.5746...  6.1990 sec/batch
Epoch: 7/20...  Training Step: 1203...  Training loss: 1.5378...  6.1235 sec/batch
Epoch: 7/20...  Training Step: 1204...  Training loss: 1.5246...  6.2994 sec/batch
Epoch: 7/20...  Training Step: 1205...  Training loss: 1.5570...  6.2113 sec/batch
Epoch: 7/20...  Training Step: 1206...  Training loss: 1.5732...  6.1286 sec/batch
Epoch: 7/20...  Training Step: 1207...  Training loss: 1.5529...  6.5972 sec/batch
Epoch: 7/20...  Training Step: 1208...  Training loss: 1.5675...  6.2194 sec/batch
Epoch: 7/20...  Training Step: 1209...  Training loss: 1.5334...  6.2278 sec/batch
Epoch: 7/20...  Training Step: 1210...  Training loss: 1.5657...  6.1068 sec/batch
Epoch: 7/20...  Training Step: 1211...  Training loss: 1.5363...  6.1637 sec/batch
Epoc

Epoch: 7/20...  Training Step: 1299...  Training loss: 1.4998...  6.0952 sec/batch
Epoch: 7/20...  Training Step: 1300...  Training loss: 1.5062...  6.1640 sec/batch
Epoch: 7/20...  Training Step: 1301...  Training loss: 1.5139...  6.1007 sec/batch
Epoch: 7/20...  Training Step: 1302...  Training loss: 1.4952...  6.2249 sec/batch
Epoch: 7/20...  Training Step: 1303...  Training loss: 1.4820...  6.2984 sec/batch
Epoch: 7/20...  Training Step: 1304...  Training loss: 1.4678...  6.1579 sec/batch
Epoch: 7/20...  Training Step: 1305...  Training loss: 1.5068...  6.1777 sec/batch
Epoch: 7/20...  Training Step: 1306...  Training loss: 1.5181...  6.1541 sec/batch
Epoch: 7/20...  Training Step: 1307...  Training loss: 1.5039...  6.2104 sec/batch
Epoch: 7/20...  Training Step: 1308...  Training loss: 1.4964...  6.2112 sec/batch
Epoch: 7/20...  Training Step: 1309...  Training loss: 1.5052...  6.1417 sec/batch
Epoch: 7/20...  Training Step: 1310...  Training loss: 1.4675...  6.1967 sec/batch
Epoc

Epoch: 8/20...  Training Step: 1398...  Training loss: 1.4750...  6.2316 sec/batch
Epoch: 8/20...  Training Step: 1399...  Training loss: 1.4837...  6.1262 sec/batch
Epoch: 8/20...  Training Step: 1400...  Training loss: 1.5107...  6.2930 sec/batch
Epoch: 8/20...  Training Step: 1401...  Training loss: 1.4783...  6.1814 sec/batch
Epoch: 8/20...  Training Step: 1402...  Training loss: 1.4662...  6.1805 sec/batch
Epoch: 8/20...  Training Step: 1403...  Training loss: 1.4954...  6.2381 sec/batch
Epoch: 8/20...  Training Step: 1404...  Training loss: 1.5194...  6.2079 sec/batch
Epoch: 8/20...  Training Step: 1405...  Training loss: 1.4917...  6.1686 sec/batch
Epoch: 8/20...  Training Step: 1406...  Training loss: 1.5148...  6.2585 sec/batch
Epoch: 8/20...  Training Step: 1407...  Training loss: 1.4831...  6.1284 sec/batch
Epoch: 8/20...  Training Step: 1408...  Training loss: 1.5000...  6.1318 sec/batch
Epoch: 8/20...  Training Step: 1409...  Training loss: 1.4673...  6.2097 sec/batch
Epoc

Epoch: 8/20...  Training Step: 1497...  Training loss: 1.4382...  6.2409 sec/batch
Epoch: 8/20...  Training Step: 1498...  Training loss: 1.4598...  6.1569 sec/batch
Epoch: 8/20...  Training Step: 1499...  Training loss: 1.4581...  7.5981 sec/batch
Epoch: 8/20...  Training Step: 1500...  Training loss: 1.4437...  6.7763 sec/batch
Epoch: 8/20...  Training Step: 1501...  Training loss: 1.4267...  6.9863 sec/batch
Epoch: 8/20...  Training Step: 1502...  Training loss: 1.4129...  6.1937 sec/batch
Epoch: 8/20...  Training Step: 1503...  Training loss: 1.4609...  6.2147 sec/batch
Epoch: 8/20...  Training Step: 1504...  Training loss: 1.4611...  6.1589 sec/batch
Epoch: 8/20...  Training Step: 1505...  Training loss: 1.4537...  6.1942 sec/batch
Epoch: 8/20...  Training Step: 1506...  Training loss: 1.4339...  6.1665 sec/batch
Epoch: 8/20...  Training Step: 1507...  Training loss: 1.4459...  6.1688 sec/batch
Epoch: 8/20...  Training Step: 1508...  Training loss: 1.4208...  6.2141 sec/batch
Epoc

Epoch: 9/20...  Training Step: 1596...  Training loss: 1.4282...  6.1858 sec/batch
Epoch: 9/20...  Training Step: 1597...  Training loss: 1.4384...  6.1394 sec/batch
Epoch: 9/20...  Training Step: 1598...  Training loss: 1.4673...  6.1208 sec/batch
Epoch: 9/20...  Training Step: 1599...  Training loss: 1.4320...  6.0915 sec/batch
Epoch: 9/20...  Training Step: 1600...  Training loss: 1.4255...  6.2074 sec/batch
Epoch: 9/20...  Training Step: 1601...  Training loss: 1.4513...  6.1494 sec/batch
Epoch: 9/20...  Training Step: 1602...  Training loss: 1.4706...  6.2084 sec/batch
Epoch: 9/20...  Training Step: 1603...  Training loss: 1.4465...  6.2202 sec/batch
Epoch: 9/20...  Training Step: 1604...  Training loss: 1.4663...  6.1699 sec/batch
Epoch: 9/20...  Training Step: 1605...  Training loss: 1.4294...  6.2059 sec/batch
Epoch: 9/20...  Training Step: 1606...  Training loss: 1.4599...  6.1408 sec/batch
Epoch: 9/20...  Training Step: 1607...  Training loss: 1.4316...  6.1593 sec/batch
Epoc

Epoch: 9/20...  Training Step: 1695...  Training loss: 1.4034...  6.1416 sec/batch
Epoch: 9/20...  Training Step: 1696...  Training loss: 1.4104...  6.2026 sec/batch
Epoch: 9/20...  Training Step: 1697...  Training loss: 1.4101...  6.1723 sec/batch
Epoch: 9/20...  Training Step: 1698...  Training loss: 1.4045...  6.1338 sec/batch
Epoch: 9/20...  Training Step: 1699...  Training loss: 1.3908...  6.2069 sec/batch
Epoch: 9/20...  Training Step: 1700...  Training loss: 1.3760...  6.1544 sec/batch
Epoch: 9/20...  Training Step: 1701...  Training loss: 1.4194...  6.1477 sec/batch
Epoch: 9/20...  Training Step: 1702...  Training loss: 1.4160...  6.1722 sec/batch
Epoch: 9/20...  Training Step: 1703...  Training loss: 1.4083...  6.1733 sec/batch
Epoch: 9/20...  Training Step: 1704...  Training loss: 1.4012...  6.1793 sec/batch
Epoch: 9/20...  Training Step: 1705...  Training loss: 1.4151...  6.1723 sec/batch
Epoch: 9/20...  Training Step: 1706...  Training loss: 1.3693...  6.2521 sec/batch
Epoc

Epoch: 10/20...  Training Step: 1794...  Training loss: 1.4000...  6.2352 sec/batch
Epoch: 10/20...  Training Step: 1795...  Training loss: 1.4029...  6.1333 sec/batch
Epoch: 10/20...  Training Step: 1796...  Training loss: 1.4307...  6.1969 sec/batch
Epoch: 10/20...  Training Step: 1797...  Training loss: 1.3897...  6.1380 sec/batch
Epoch: 10/20...  Training Step: 1798...  Training loss: 1.3812...  6.1612 sec/batch
Epoch: 10/20...  Training Step: 1799...  Training loss: 1.4163...  6.1859 sec/batch
Epoch: 10/20...  Training Step: 1800...  Training loss: 1.4329...  6.1392 sec/batch
Epoch: 10/20...  Training Step: 1801...  Training loss: 1.4095...  6.1800 sec/batch
Epoch: 10/20...  Training Step: 1802...  Training loss: 1.4326...  6.1827 sec/batch
Epoch: 10/20...  Training Step: 1803...  Training loss: 1.3939...  6.1979 sec/batch
Epoch: 10/20...  Training Step: 1804...  Training loss: 1.4162...  6.2862 sec/batch
Epoch: 10/20...  Training Step: 1805...  Training loss: 1.4026...  6.2211 se

Epoch: 10/20...  Training Step: 1892...  Training loss: 1.3988...  7.9619 sec/batch
Epoch: 10/20...  Training Step: 1893...  Training loss: 1.3678...  6.2288 sec/batch
Epoch: 10/20...  Training Step: 1894...  Training loss: 1.3829...  6.1143 sec/batch
Epoch: 10/20...  Training Step: 1895...  Training loss: 1.3889...  6.2365 sec/batch
Epoch: 10/20...  Training Step: 1896...  Training loss: 1.3733...  6.2046 sec/batch
Epoch: 10/20...  Training Step: 1897...  Training loss: 1.3596...  6.1974 sec/batch
Epoch: 10/20...  Training Step: 1898...  Training loss: 1.3448...  6.2066 sec/batch
Epoch: 10/20...  Training Step: 1899...  Training loss: 1.3854...  6.2427 sec/batch
Epoch: 10/20...  Training Step: 1900...  Training loss: 1.3929...  6.1270 sec/batch
Epoch: 10/20...  Training Step: 1901...  Training loss: 1.3792...  6.1647 sec/batch
Epoch: 10/20...  Training Step: 1902...  Training loss: 1.3659...  6.1809 sec/batch
Epoch: 10/20...  Training Step: 1903...  Training loss: 1.3754...  6.1555 se

Epoch: 11/20...  Training Step: 1990...  Training loss: 1.3729...  6.1567 sec/batch
Epoch: 11/20...  Training Step: 1991...  Training loss: 1.3669...  6.2079 sec/batch
Epoch: 11/20...  Training Step: 1992...  Training loss: 1.3657...  6.1518 sec/batch
Epoch: 11/20...  Training Step: 1993...  Training loss: 1.3701...  6.3778 sec/batch
Epoch: 11/20...  Training Step: 1994...  Training loss: 1.3939...  6.4505 sec/batch
Epoch: 11/20...  Training Step: 1995...  Training loss: 1.3765...  6.4638 sec/batch
Epoch: 11/20...  Training Step: 1996...  Training loss: 1.3573...  6.4017 sec/batch
Epoch: 11/20...  Training Step: 1997...  Training loss: 1.3856...  6.3656 sec/batch
Epoch: 11/20...  Training Step: 1998...  Training loss: 1.3978...  6.8182 sec/batch
Epoch: 11/20...  Training Step: 1999...  Training loss: 1.3738...  6.4983 sec/batch
Epoch: 11/20...  Training Step: 2000...  Training loss: 1.4069...  6.4569 sec/batch
Epoch: 11/20...  Training Step: 2001...  Training loss: 1.3810...  6.3989 se

Epoch: 11/20...  Training Step: 2088...  Training loss: 1.3593...  6.5957 sec/batch
Epoch: 11/20...  Training Step: 2089...  Training loss: 1.3489...  6.1043 sec/batch
Epoch: 11/20...  Training Step: 2090...  Training loss: 1.3716...  6.1480 sec/batch
Epoch: 11/20...  Training Step: 2091...  Training loss: 1.3407...  6.1135 sec/batch
Epoch: 11/20...  Training Step: 2092...  Training loss: 1.3553...  6.1689 sec/batch
Epoch: 11/20...  Training Step: 2093...  Training loss: 1.3589...  6.2171 sec/batch
Epoch: 11/20...  Training Step: 2094...  Training loss: 1.3445...  6.2141 sec/batch
Epoch: 11/20...  Training Step: 2095...  Training loss: 1.3342...  6.1690 sec/batch
Epoch: 11/20...  Training Step: 2096...  Training loss: 1.3240...  6.5191 sec/batch
Epoch: 11/20...  Training Step: 2097...  Training loss: 1.3571...  6.1200 sec/batch
Epoch: 11/20...  Training Step: 2098...  Training loss: 1.3687...  6.2499 sec/batch
Epoch: 11/20...  Training Step: 2099...  Training loss: 1.3450...  6.1798 se

Epoch: 12/20...  Training Step: 2186...  Training loss: 1.3429...  7.1569 sec/batch
Epoch: 12/20...  Training Step: 2187...  Training loss: 1.3556...  7.5608 sec/batch
Epoch: 12/20...  Training Step: 2188...  Training loss: 1.3513...  7.9615 sec/batch
Epoch: 12/20...  Training Step: 2189...  Training loss: 1.3343...  9.8146 sec/batch
Epoch: 12/20...  Training Step: 2190...  Training loss: 1.3461...  9.3824 sec/batch
Epoch: 12/20...  Training Step: 2191...  Training loss: 1.3543...  8.5609 sec/batch
Epoch: 12/20...  Training Step: 2192...  Training loss: 1.3673...  8.5192 sec/batch
Epoch: 12/20...  Training Step: 2193...  Training loss: 1.3387...  9.2103 sec/batch
Epoch: 12/20...  Training Step: 2194...  Training loss: 1.3177...  8.2089 sec/batch
Epoch: 12/20...  Training Step: 2195...  Training loss: 1.3696...  7.5188 sec/batch
Epoch: 12/20...  Training Step: 2196...  Training loss: 1.3731...  7.4512 sec/batch
Epoch: 12/20...  Training Step: 2197...  Training loss: 1.3535...  6.6981 se

Epoch: 12/20...  Training Step: 2284...  Training loss: 1.3301...  7.3405 sec/batch
Epoch: 12/20...  Training Step: 2285...  Training loss: 1.3420...  7.5643 sec/batch
Epoch: 12/20...  Training Step: 2286...  Training loss: 1.3410...  7.2125 sec/batch
Epoch: 12/20...  Training Step: 2287...  Training loss: 1.3237...  6.9137 sec/batch
Epoch: 12/20...  Training Step: 2288...  Training loss: 1.3527...  6.3738 sec/batch
Epoch: 12/20...  Training Step: 2289...  Training loss: 1.3263...  6.1621 sec/batch
Epoch: 12/20...  Training Step: 2290...  Training loss: 1.3389...  6.1436 sec/batch
Epoch: 12/20...  Training Step: 2291...  Training loss: 1.3397...  6.1644 sec/batch
Epoch: 12/20...  Training Step: 2292...  Training loss: 1.3297...  6.1358 sec/batch
Epoch: 12/20...  Training Step: 2293...  Training loss: 1.3166...  6.2827 sec/batch
Epoch: 12/20...  Training Step: 2294...  Training loss: 1.2964...  6.6041 sec/batch
Epoch: 12/20...  Training Step: 2295...  Training loss: 1.3376...  6.4414 se

Epoch: 13/20...  Training Step: 2382...  Training loss: 1.2996...  6.6668 sec/batch
Epoch: 13/20...  Training Step: 2383...  Training loss: 1.3399...  7.4574 sec/batch
Epoch: 13/20...  Training Step: 2384...  Training loss: 1.3167...  8.5192 sec/batch
Epoch: 13/20...  Training Step: 2385...  Training loss: 1.3415...  6.7569 sec/batch
Epoch: 13/20...  Training Step: 2386...  Training loss: 1.3324...  6.8155 sec/batch
Epoch: 13/20...  Training Step: 2387...  Training loss: 1.3139...  7.2927 sec/batch
Epoch: 13/20...  Training Step: 2388...  Training loss: 1.3192...  7.0693 sec/batch
Epoch: 13/20...  Training Step: 2389...  Training loss: 1.3269...  6.5888 sec/batch
Epoch: 13/20...  Training Step: 2390...  Training loss: 1.3383...  6.2639 sec/batch
Epoch: 13/20...  Training Step: 2391...  Training loss: 1.3084...  6.2071 sec/batch
Epoch: 13/20...  Training Step: 2392...  Training loss: 1.3033...  6.6015 sec/batch
Epoch: 13/20...  Training Step: 2393...  Training loss: 1.3307...  7.0197 se

Epoch: 13/20...  Training Step: 2480...  Training loss: 1.3036...  7.4084 sec/batch
Epoch: 13/20...  Training Step: 2481...  Training loss: 1.3078...  7.0867 sec/batch
Epoch: 13/20...  Training Step: 2482...  Training loss: 1.3108...  6.4762 sec/batch
Epoch: 13/20...  Training Step: 2483...  Training loss: 1.3170...  7.5394 sec/batch
Epoch: 13/20...  Training Step: 2484...  Training loss: 1.3139...  11.0419 sec/batch
Epoch: 13/20...  Training Step: 2485...  Training loss: 1.3074...  8.6519 sec/batch
Epoch: 13/20...  Training Step: 2486...  Training loss: 1.3215...  7.0812 sec/batch
Epoch: 13/20...  Training Step: 2487...  Training loss: 1.2966...  6.4143 sec/batch
Epoch: 13/20...  Training Step: 2488...  Training loss: 1.3181...  6.2173 sec/batch
Epoch: 13/20...  Training Step: 2489...  Training loss: 1.3221...  6.3176 sec/batch
Epoch: 13/20...  Training Step: 2490...  Training loss: 1.3056...  6.2290 sec/batch
Epoch: 13/20...  Training Step: 2491...  Training loss: 1.2925...  6.1304 s

Epoch: 14/20...  Training Step: 2578...  Training loss: 1.3286...  6.2448 sec/batch
Epoch: 14/20...  Training Step: 2579...  Training loss: 1.2975...  6.1071 sec/batch
Epoch: 14/20...  Training Step: 2580...  Training loss: 1.2696...  6.1997 sec/batch
Epoch: 14/20...  Training Step: 2581...  Training loss: 1.3101...  6.1589 sec/batch
Epoch: 14/20...  Training Step: 2582...  Training loss: 1.2981...  6.2475 sec/batch
Epoch: 14/20...  Training Step: 2583...  Training loss: 1.3013...  6.1501 sec/batch
Epoch: 14/20...  Training Step: 2584...  Training loss: 1.3061...  6.0928 sec/batch
Epoch: 14/20...  Training Step: 2585...  Training loss: 1.2926...  6.2796 sec/batch
Epoch: 14/20...  Training Step: 2586...  Training loss: 1.3086...  6.1318 sec/batch
Epoch: 14/20...  Training Step: 2587...  Training loss: 1.3037...  6.0726 sec/batch
Epoch: 14/20...  Training Step: 2588...  Training loss: 1.3166...  6.3607 sec/batch
Epoch: 14/20...  Training Step: 2589...  Training loss: 1.2863...  6.2785 se

Epoch: 14/20...  Training Step: 2675...  Training loss: 1.3042...  41.5146 sec/batch
Epoch: 14/20...  Training Step: 2676...  Training loss: 1.2851...  39.7088 sec/batch
Epoch: 14/20...  Training Step: 2677...  Training loss: 1.2966...  40.3652 sec/batch
Epoch: 14/20...  Training Step: 2678...  Training loss: 1.2892...  41.4755 sec/batch
Epoch: 14/20...  Training Step: 2679...  Training loss: 1.2926...  39.4293 sec/batch
Epoch: 14/20...  Training Step: 2680...  Training loss: 1.2861...  39.9943 sec/batch
Epoch: 14/20...  Training Step: 2681...  Training loss: 1.3020...  41.1428 sec/batch
Epoch: 14/20...  Training Step: 2682...  Training loss: 1.3036...  40.3946 sec/batch
Epoch: 14/20...  Training Step: 2683...  Training loss: 1.2815...  43.2634 sec/batch
Epoch: 14/20...  Training Step: 2684...  Training loss: 1.2989...  40.7817 sec/batch
Epoch: 14/20...  Training Step: 2685...  Training loss: 1.2810...  40.6678 sec/batch
Epoch: 14/20...  Training Step: 2686...  Training loss: 1.2991...

Epoch: 14/20...  Training Step: 2772...  Training loss: 1.2741...  42.7433 sec/batch
Epoch: 15/20...  Training Step: 2773...  Training loss: 1.4152...  41.0659 sec/batch
Epoch: 15/20...  Training Step: 2774...  Training loss: 1.3079...  40.7462 sec/batch
Epoch: 15/20...  Training Step: 2775...  Training loss: 1.2978...  39.6571 sec/batch
Epoch: 15/20...  Training Step: 2776...  Training loss: 1.3182...  41.0867 sec/batch
Epoch: 15/20...  Training Step: 2777...  Training loss: 1.2746...  41.0785 sec/batch
Epoch: 15/20...  Training Step: 2778...  Training loss: 1.2601...  39.6383 sec/batch
Epoch: 15/20...  Training Step: 2779...  Training loss: 1.3041...  41.2252 sec/batch
Epoch: 15/20...  Training Step: 2780...  Training loss: 1.2859...  43.2539 sec/batch
Epoch: 15/20...  Training Step: 2781...  Training loss: 1.3041...  40.1954 sec/batch
Epoch: 15/20...  Training Step: 2782...  Training loss: 1.2906...  40.2769 sec/batch
Epoch: 15/20...  Training Step: 2783...  Training loss: 1.2813...

Epoch: 15/20...  Training Step: 2869...  Training loss: 1.2900...  42.3379 sec/batch
Epoch: 15/20...  Training Step: 2870...  Training loss: 1.2584...  39.9937 sec/batch
Epoch: 15/20...  Training Step: 2871...  Training loss: 1.2649...  41.4673 sec/batch
Epoch: 15/20...  Training Step: 2872...  Training loss: 1.2537...  39.9464 sec/batch
Epoch: 15/20...  Training Step: 2873...  Training loss: 1.2885...  39.7667 sec/batch
Epoch: 15/20...  Training Step: 2874...  Training loss: 1.2785...  42.4474 sec/batch
Epoch: 15/20...  Training Step: 2875...  Training loss: 1.2777...  40.7781 sec/batch
Epoch: 15/20...  Training Step: 2876...  Training loss: 1.2671...  39.8710 sec/batch
Epoch: 15/20...  Training Step: 2877...  Training loss: 1.2833...  44.4926 sec/batch
Epoch: 15/20...  Training Step: 2878...  Training loss: 1.2780...  40.0024 sec/batch
Epoch: 15/20...  Training Step: 2879...  Training loss: 1.2856...  40.7519 sec/batch
Epoch: 15/20...  Training Step: 2880...  Training loss: 1.2992...

Epoch: 15/20...  Training Step: 2966...  Training loss: 1.2488...  43.4288 sec/batch
Epoch: 15/20...  Training Step: 2967...  Training loss: 1.2343...  39.8457 sec/batch
Epoch: 15/20...  Training Step: 2968...  Training loss: 1.2787...  40.5354 sec/batch
Epoch: 15/20...  Training Step: 2969...  Training loss: 1.2672...  41.7157 sec/batch
Epoch: 15/20...  Training Step: 2970...  Training loss: 1.2623...  40.3333 sec/batch
Epoch: 16/20...  Training Step: 2971...  Training loss: 1.3969...  39.9105 sec/batch
Epoch: 16/20...  Training Step: 2972...  Training loss: 1.2836...  41.1361 sec/batch
Epoch: 16/20...  Training Step: 2973...  Training loss: 1.2741...  39.7395 sec/batch
Epoch: 16/20...  Training Step: 2974...  Training loss: 1.3039...  42.3729 sec/batch
Epoch: 16/20...  Training Step: 2975...  Training loss: 1.2581...  40.8980 sec/batch
Epoch: 16/20...  Training Step: 2976...  Training loss: 1.2417...  40.2941 sec/batch
Epoch: 16/20...  Training Step: 2977...  Training loss: 1.2884...

Epoch: 16/20...  Training Step: 3063...  Training loss: 1.2409...  40.3123 sec/batch
Epoch: 16/20...  Training Step: 3064...  Training loss: 1.2465...  40.9232 sec/batch
Epoch: 16/20...  Training Step: 3065...  Training loss: 1.2493...  40.1896 sec/batch
Epoch: 16/20...  Training Step: 3066...  Training loss: 1.2844...  40.8436 sec/batch
Epoch: 16/20...  Training Step: 3067...  Training loss: 1.2734...  41.1155 sec/batch
Epoch: 16/20...  Training Step: 3068...  Training loss: 1.2400...  40.7875 sec/batch
Epoch: 16/20...  Training Step: 3069...  Training loss: 1.2438...  42.9133 sec/batch
Epoch: 16/20...  Training Step: 3070...  Training loss: 1.2379...  39.8047 sec/batch
Epoch: 16/20...  Training Step: 3071...  Training loss: 1.2699...  40.3475 sec/batch
Epoch: 16/20...  Training Step: 3072...  Training loss: 1.2558...  40.5289 sec/batch
Epoch: 16/20...  Training Step: 3073...  Training loss: 1.2684...  40.0626 sec/batch
Epoch: 16/20...  Training Step: 3074...  Training loss: 1.2559...

Epoch: 16/20...  Training Step: 3160...  Training loss: 1.2587...  40.1372 sec/batch
Epoch: 16/20...  Training Step: 3161...  Training loss: 1.2403...  40.7255 sec/batch
Epoch: 16/20...  Training Step: 3162...  Training loss: 1.2509...  40.2668 sec/batch
Epoch: 16/20...  Training Step: 3163...  Training loss: 1.2673...  40.4210 sec/batch
Epoch: 16/20...  Training Step: 3164...  Training loss: 1.2458...  41.7561 sec/batch
Epoch: 16/20...  Training Step: 3165...  Training loss: 1.2260...  39.9195 sec/batch
Epoch: 16/20...  Training Step: 3166...  Training loss: 1.2632...  42.1902 sec/batch
Epoch: 16/20...  Training Step: 3167...  Training loss: 1.2538...  41.3814 sec/batch
Epoch: 16/20...  Training Step: 3168...  Training loss: 1.2550...  40.2978 sec/batch
Epoch: 17/20...  Training Step: 3169...  Training loss: 1.3731...  41.1701 sec/batch
Epoch: 17/20...  Training Step: 3170...  Training loss: 1.2700...  40.7485 sec/batch
Epoch: 17/20...  Training Step: 3171...  Training loss: 1.2651...

Epoch: 17/20...  Training Step: 3257...  Training loss: 1.2237...  9.7024 sec/batch
Epoch: 17/20...  Training Step: 3258...  Training loss: 1.2588...  36.5451 sec/batch
Epoch: 17/20...  Training Step: 3259...  Training loss: 1.2338...  7.1616 sec/batch
Epoch: 17/20...  Training Step: 3260...  Training loss: 1.2472...  8.9008 sec/batch
Epoch: 17/20...  Training Step: 3261...  Training loss: 1.2381...  10.1148 sec/batch
Epoch: 17/20...  Training Step: 3262...  Training loss: 1.2302...  27.6461 sec/batch
Epoch: 17/20...  Training Step: 3263...  Training loss: 1.2375...  7.4371 sec/batch
Epoch: 17/20...  Training Step: 3264...  Training loss: 1.2642...  9.9415 sec/batch
Epoch: 17/20...  Training Step: 3265...  Training loss: 1.2641...  10.0567 sec/batch
Epoch: 17/20...  Training Step: 3266...  Training loss: 1.2238...  47.5462 sec/batch
Epoch: 17/20...  Training Step: 3267...  Training loss: 1.2376...  7.9733 sec/batch
Epoch: 17/20...  Training Step: 3268...  Training loss: 1.2294...  11.7

Epoch: 17/20...  Training Step: 3355...  Training loss: 1.2727...  12.1656 sec/batch
Epoch: 17/20...  Training Step: 3356...  Training loss: 1.2429...  12.4114 sec/batch
Epoch: 17/20...  Training Step: 3357...  Training loss: 1.2491...  12.1941 sec/batch
Epoch: 17/20...  Training Step: 3358...  Training loss: 1.2487...  12.0414 sec/batch
Epoch: 17/20...  Training Step: 3359...  Training loss: 1.2224...  16.2235 sec/batch
Epoch: 17/20...  Training Step: 3360...  Training loss: 1.2407...  12.0725 sec/batch
Epoch: 17/20...  Training Step: 3361...  Training loss: 1.2608...  12.1585 sec/batch
Epoch: 17/20...  Training Step: 3362...  Training loss: 1.2463...  12.1350 sec/batch
Epoch: 17/20...  Training Step: 3363...  Training loss: 1.2060...  12.0311 sec/batch
Epoch: 17/20...  Training Step: 3364...  Training loss: 1.2503...  12.1049 sec/batch
Epoch: 17/20...  Training Step: 3365...  Training loss: 1.2357...  11.9610 sec/batch
Epoch: 17/20...  Training Step: 3366...  Training loss: 1.2367...

Epoch: 18/20...  Training Step: 3452...  Training loss: 1.2418...  13.3403 sec/batch
Epoch: 18/20...  Training Step: 3453...  Training loss: 1.2258...  13.5892 sec/batch
Epoch: 18/20...  Training Step: 3454...  Training loss: 1.2203...  15.0724 sec/batch
Epoch: 18/20...  Training Step: 3455...  Training loss: 1.2179...  15.6718 sec/batch
Epoch: 18/20...  Training Step: 3456...  Training loss: 1.2471...  14.3535 sec/batch
Epoch: 18/20...  Training Step: 3457...  Training loss: 1.2142...  13.9965 sec/batch
Epoch: 18/20...  Training Step: 3458...  Training loss: 1.2357...  16.7808 sec/batch
Epoch: 18/20...  Training Step: 3459...  Training loss: 1.2223...  16.7524 sec/batch
Epoch: 18/20...  Training Step: 3460...  Training loss: 1.2159...  14.4169 sec/batch
Epoch: 18/20...  Training Step: 3461...  Training loss: 1.2242...  20.3330 sec/batch
Epoch: 18/20...  Training Step: 3462...  Training loss: 1.2473...  18.5765 sec/batch
Epoch: 18/20...  Training Step: 3463...  Training loss: 1.2557...

Epoch: 18/20...  Training Step: 3549...  Training loss: 1.2368...  12.0161 sec/batch
Epoch: 18/20...  Training Step: 3550...  Training loss: 1.2303...  12.6360 sec/batch
Epoch: 18/20...  Training Step: 3551...  Training loss: 1.2344...  12.7596 sec/batch
Epoch: 18/20...  Training Step: 3552...  Training loss: 1.2202...  12.0228 sec/batch
Epoch: 18/20...  Training Step: 3553...  Training loss: 1.2725...  12.0717 sec/batch
Epoch: 18/20...  Training Step: 3554...  Training loss: 1.2310...  12.2832 sec/batch
Epoch: 18/20...  Training Step: 3555...  Training loss: 1.2397...  12.0673 sec/batch
Epoch: 18/20...  Training Step: 3556...  Training loss: 1.2429...  12.0844 sec/batch
Epoch: 18/20...  Training Step: 3557...  Training loss: 1.2182...  12.8491 sec/batch
Epoch: 18/20...  Training Step: 3558...  Training loss: 1.2212...  12.2941 sec/batch
Epoch: 18/20...  Training Step: 3559...  Training loss: 1.2476...  12.0556 sec/batch
Epoch: 18/20...  Training Step: 3560...  Training loss: 1.2268...

Epoch: 19/20...  Training Step: 3646...  Training loss: 1.2401...  12.1131 sec/batch
Epoch: 19/20...  Training Step: 3647...  Training loss: 1.2073...  11.8869 sec/batch
Epoch: 19/20...  Training Step: 3648...  Training loss: 1.2186...  12.0003 sec/batch
Epoch: 19/20...  Training Step: 3649...  Training loss: 1.2120...  12.2223 sec/batch
Epoch: 19/20...  Training Step: 3650...  Training loss: 1.2282...  11.9688 sec/batch
Epoch: 19/20...  Training Step: 3651...  Training loss: 1.2099...  12.1398 sec/batch
Epoch: 19/20...  Training Step: 3652...  Training loss: 1.2211...  11.9932 sec/batch
Epoch: 19/20...  Training Step: 3653...  Training loss: 1.2037...  12.0801 sec/batch
Epoch: 19/20...  Training Step: 3654...  Training loss: 1.2396...  12.0177 sec/batch
Epoch: 19/20...  Training Step: 3655...  Training loss: 1.2146...  14.2306 sec/batch
Epoch: 19/20...  Training Step: 3656...  Training loss: 1.2146...  13.0429 sec/batch
Epoch: 19/20...  Training Step: 3657...  Training loss: 1.2187...

Epoch: 19/20...  Training Step: 3743...  Training loss: 1.2101...  11.8892 sec/batch
Epoch: 19/20...  Training Step: 3744...  Training loss: 1.2040...  12.0970 sec/batch
Epoch: 19/20...  Training Step: 3745...  Training loss: 1.2271...  11.9087 sec/batch
Epoch: 19/20...  Training Step: 3746...  Training loss: 1.2321...  12.0251 sec/batch
Epoch: 19/20...  Training Step: 3747...  Training loss: 1.2276...  11.9808 sec/batch
Epoch: 19/20...  Training Step: 3748...  Training loss: 1.2256...  11.9221 sec/batch
Epoch: 19/20...  Training Step: 3749...  Training loss: 1.2191...  12.1664 sec/batch
Epoch: 19/20...  Training Step: 3750...  Training loss: 1.2038...  12.0404 sec/batch
Epoch: 19/20...  Training Step: 3751...  Training loss: 1.2582...  11.8560 sec/batch
Epoch: 19/20...  Training Step: 3752...  Training loss: 1.2239...  12.0373 sec/batch
Epoch: 19/20...  Training Step: 3753...  Training loss: 1.2189...  12.0167 sec/batch
Epoch: 19/20...  Training Step: 3754...  Training loss: 1.2279...

Epoch: 20/20...  Training Step: 3840...  Training loss: 1.2096...  13.9281 sec/batch
Epoch: 20/20...  Training Step: 3841...  Training loss: 1.1821...  13.5955 sec/batch
Epoch: 20/20...  Training Step: 3842...  Training loss: 1.2383...  13.4626 sec/batch
Epoch: 20/20...  Training Step: 3843...  Training loss: 1.1840...  13.5730 sec/batch
Epoch: 20/20...  Training Step: 3844...  Training loss: 1.2335...  14.1840 sec/batch
Epoch: 20/20...  Training Step: 3845...  Training loss: 1.1976...  14.0467 sec/batch
Epoch: 20/20...  Training Step: 3846...  Training loss: 1.2140...  14.3208 sec/batch
Epoch: 20/20...  Training Step: 3847...  Training loss: 1.1930...  13.8428 sec/batch
Epoch: 20/20...  Training Step: 3848...  Training loss: 1.2177...  13.6184 sec/batch
Epoch: 20/20...  Training Step: 3849...  Training loss: 1.1885...  14.6241 sec/batch
Epoch: 20/20...  Training Step: 3850...  Training loss: 1.2049...  14.1863 sec/batch
Epoch: 20/20...  Training Step: 3851...  Training loss: 1.1943...

Epoch: 20/20...  Training Step: 3937...  Training loss: 1.2333...  13.6795 sec/batch
Epoch: 20/20...  Training Step: 3938...  Training loss: 1.1919...  13.3156 sec/batch
Epoch: 20/20...  Training Step: 3939...  Training loss: 1.2157...  13.6288 sec/batch
Epoch: 20/20...  Training Step: 3940...  Training loss: 1.2571...  14.4118 sec/batch
Epoch: 20/20...  Training Step: 3941...  Training loss: 1.2004...  12.8330 sec/batch
Epoch: 20/20...  Training Step: 3942...  Training loss: 1.1982...  12.9520 sec/batch
Epoch: 20/20...  Training Step: 3943...  Training loss: 1.2150...  13.0021 sec/batch
Epoch: 20/20...  Training Step: 3944...  Training loss: 1.2177...  14.5905 sec/batch
Epoch: 20/20...  Training Step: 3945...  Training loss: 1.2117...  15.5497 sec/batch
Epoch: 20/20...  Training Step: 3946...  Training loss: 1.2160...  14.1428 sec/batch
Epoch: 20/20...  Training Step: 3947...  Training loss: 1.2102...  14.5266 sec/batch
Epoch: 20/20...  Training Step: 3948...  Training loss: 1.2070...

#### Saved checkpoints

Read up on saving and loading checkpoints here: https://www.tensorflow.org/programmers_guide/variables

In [18]:
tf.train.get_checkpoint_state('checkpoints')

model_checkpoint_path: "checkpoints/i3960_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i3000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i3200_l512.ckpt"
all_model_checkpoint_pa

## Sampling

Now that the network is trained, we'll can use it to generate new text. The idea is that we pass in a character, then the network will predict the next character. We can use the new one, to predict the next one. And we keep doing this to generate all new text. I also included some functionality to prime the network with some text by passing in a string and building up a state from that.

The network gives us predictions for each character. To reduce noise and make things a little less random, I'm going to only choose a new character from the top N most likely characters.



In [19]:
def pick_top_n(preds, vocab_size, top_n=5):
    p = np.squeeze(preds)
    p[np.argsort(p)[:-top_n]] = 0
    p = p / np.sum(p)
    c = np.random.choice(vocab_size, 1, p=p)[0]
    return c

In [20]:
def sample(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = [c for c in prime]
    model = CharRNN(len(vocab), lstm_size=lstm_size, sampling=True)
    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(model.initial_state)
        for c in prime:
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

        c = pick_top_n(preds, len(vocab))
        samples.append(int_to_vocab[c])

        for i in range(n_samples):
            x[0,0] = c
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

            c = pick_top_n(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples)

Here, pass in the path to a checkpoint and sample from the network.

In [21]:
tf.train.latest_checkpoint('checkpoints')

'checkpoints/i3960_l512.ckpt'

In [22]:
checkpoint = tf.train.latest_checkpoint('checkpoints')
samp = sample(checkpoint, 2000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i3960_l512.ckpt
Farred of them,
she said that she could not have liked to say, having not baren
and shameful to his short of the position. She was in the table
and started, and hid because she her husband was not all so seeing, but
he came back to the best forese and many sound of anticipalies, but she
would so lively, that he did not see the same afternation. And with a
creature to this way of his happiness in the moment.

"What are you someone for? The prince was a long while that's a minute to
think is at the coupt of the same at all," she answered.

"All I am so song of your honest."

And he should not care to see him when he had to go to her.

"Yes, I'm never been work and more attracting her of it," said Stepan
Arkadyevitch, still half-past the princess. "I shall be in a country
done," he thought that the corrept and a shrewd of the conversation of
the book in the doorway. "In it and has stood it."

"Well, and would be a sayin

In [ ]:
checkpoint = 'checkpoints/i200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i200_l512.ckpt
Farg,.

"W"hh sos
sean thed the with winte wo he his ane ad th ant wate thed an theres thor th wimhe he wotes.

"Wh t ald tho shen tor he whos anes of hos he th siton ot the won the hersos one the she warigind sor ho te whed an oto sor he thim wasesid andind art ot tore ang an ot has
eranded sou thit he hons ofes wond the sing the asd aned ther thas at as ar hire ha he han this toring ant an or hin the timense the
sane tathe ante ad al oo wher whe had
at at oo los tire an thim he whar thit
he thet to the and and the he wes tas hes and he han ad ar te hissas, the he her on tete the and onging on tor that asd ang ond hin that to win athe whe wot ta the woris hir seasd se and tis he hers hans wang and oun and, he anten as on thin shared ar herans ond ong than an sont ond an hot tes he sher tha we and the hun sher, sane has ood tat an he an hit asd or wint tho ther wan sasd, wad the han than he ale watit

ateten, win hat 

In [ ]:
checkpoint = 'checkpoints/i600_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i600_l512.ckpt


In [ ]:
checkpoint = 'checkpoints/i1200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)